spring.application.name=recruitEdge
# server.port=${PORT:8080}
server.port=8080

# Database
# spring.data.mongodb.uri=mongodb+srv://gfjh:bghbgj@cluster0.ubgrgul.mongodb.net/?appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://dhyaneshdharmikdd_db_user:Saibaba25@cluster0.ubgrgul.mongodb.net/recruitEdge?retryWrites=true&w=majority

# JWT
jwt.secret=mysupersecuresecretkeymysupersecuresecretkey
jwt.expiration=3600000

# Google Clientid
google.client-id=1059696075673-rhtifjsdagqsq7d911jg2vsbo803m63s.apps.googleusercontent.com

