spring.application.name=recruitEdge
server.port=${PORT:8080}

# Database
# spring.data.mongodb.uri=mongodb+srv://gfjh:bghbgj@cluster0.ubgrgul.mongodb.net/?appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://dhyaneshdharmikdd_db_user:Saibaba25@cluster0.ubgrgul.mongodb.net/recruitEdge?retryWrites=true&w=majority

# JWT
jwt.secret=mysupersecuresecretkeymysupersecuresecretkey
jwt.expiration=3600000


